### PR TITLE
Added support for MailChimp variable syntax

### PR DESCRIPTION
**Pull request by ArneZsng**
Hacked together support for moving from MailChimp variable syntax to handlebars. Feel free to use it if you can.

### CODE REVIEW

**Comment by ewandennis** [comment]
This looks great, thanks for the contribution.  We might want to update the *Supported Features* bullets in `README.md` and `static/index.html` to publicise your new feature, though.  D'you agree?

**Comment by ewandennis** [comment]
For reference, I believe the correct name for these `*|variables|*` is Mailchimp *merge tags*.

**Comment by ArneZsng** [comment]
I'll update it accordingly. :)






On Thu, Mar 24, 2016 at 3:22 AM -0700, "Ewan Dennis" <notifications@github.com> wrote:












For reference, I believe the correct name for these *|variables|* is Mailchimp merge tags.

**Comment by ArneZsng** [comment]
@ewandennis Updated.

**Comment by ewandennis** [comment]
Perfect - merging.  Thanks again - this is a great contribution.

**Pull request merged**
